### ISSUE TITLE
Node Rename and delete option

### ISSUE THREAD

**Issue by Abhijeet501** [naisutech/react-tree#35]
Hello Is there a Node(folder) rename and Delete option in the current tree? 
If we can do that please let me know 
I appreciate your help thanks!

**Comment by ortonomy** [comment]
The rename or delete functionality would be down to you, as a developer and what you want to implement. 

I think it would be a good idea to provide a `nodeRenderer` prop to the API so that you could implement your own content in the node which would carry this functionality.

This is more of a 'react way' of doing things.

**Comment by ortonomy** [comment]
Hi @Abhijeet501 -- thanks for your question and inspiration for v2 of react tree. You can now achieve what you're looking for by creating a `NodeRenderer` or `ElementRenderer` yourself and putting an input field linked to your own change event listener to update the data in your tree. 

See: 

- https://github.com/naisutech/react-tree/releases/tag/2.0.0
- https://naisutech.github.io/react-tree/?path=/story/react-tree--custom-nodes-and-leaves
