### ISSUE TITLE
Right click behavior

### ISSUE THREAD

**Issue by martinRenou** [naisutech/react-tree#82]
Thanks for this extension!

I'd like to implement a right-click behavior on my tree. It would be useful to have some kind of `onClick` property which would accept a callback like `(e: MouseEvent, id: TreeNodeId) => void`.

Is this possible already?

**Comment by ortonomy** [comment]
Hi, @martinRenou  - thanks for opening this issue. I had no plans to add an onclick event, but if others ask for it, I can.

You should be able to pass a custom renderer and the you can bind a click listener to the elements you render there. Don't forget to stop the propagation, though. Otherwise the click listeners for open/and select will still fire.
